//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IdealMall.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class CashAndCarry
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CashAndCarry()
        {
            this.ShoppingList_Trade = new HashSet<ShoppingList_Trade>();
        }
    
        public int Shop_Id { get; set; }
        public string Shop_Name { get; set; }
        public string Shop_ImageURL { get; set; }
        public string Available { get; set; }
        public string Type { get; set; }
        public string Live_Available { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ShoppingList_Trade> ShoppingList_Trade { get; set; }
    }
}
