//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IdealMall.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class Login_Public
    {
        public string UserId { get; set; }
        public string PostCode { get; set; }
        public System.DateTime DateInserted { get; set; }
        public string User_Password { get; set; }
        public string IsActive { get; set; }
    }
}
