//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IdealMall.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class OfferProducts_Trade
    {
        public int OfferProducts_Id { get; set; }
        public Nullable<int> Shop_Id { get; set; }
        public Nullable<decimal> Offer_Rate { get; set; }
        public string Volume { get; set; }
        public string PostCode { get; set; }
        public string Product_ImageURL { get; set; }
        public Nullable<decimal> Max_Retail_Price { get; set; }
        public System.DateTime DateInserted { get; set; }
        public Nullable<decimal> POR { get; set; }
        public Nullable<decimal> VAT { get; set; }
        public string Product { get; set; }
        public string Category { get; set; }
        public string Additional_Offer { get; set; }
        public Nullable<System.DateTime> Offer_Enddate { get; set; }
        public string Department { get; set; }
        public string Additional_Info { get; set; }
    }
}
