//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IdealMall.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class Retailshop
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Retailshop()
        {
            this.OfferProducts_Public = new HashSet<OfferProducts_Public>();
            this.ShoppingList_Public = new HashSet<ShoppingList_Public>();
            this.ShoppingList_Public1 = new HashSet<ShoppingList_Public>();
            this.ShoppingList_Public2 = new HashSet<ShoppingList_Public>();
        }
    
        public int Shop_Id { get; set; }
        public string Shop_Name { get; set; }
        public string Shop_ImageURL { get; set; }
        public string Postcode { get; set; }
        public string Address { get; set; }
        public string Available { get; set; }
        public string Shop_Orginal_Name { get; set; }
        public string Services { get; set; }
        public string Services_Text { get; set; }
        public string shopping_Timing { get; set; }
        public string PhoneNumber { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OfferProducts_Public> OfferProducts_Public { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ShoppingList_Public> ShoppingList_Public { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ShoppingList_Public> ShoppingList_Public1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ShoppingList_Public> ShoppingList_Public2 { get; set; }
    }
}
