//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IdealMall.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class ShoppingList_Public
    {
        public int Shopping_Id { get; set; }
        public string UserId { get; set; }
        public Nullable<int> Shop_Id { get; set; }
        public string Product { get; set; }
        public Nullable<decimal> Offer_Rate { get; set; }
        public string Volume { get; set; }
        public Nullable<int> Qty { get; set; }
        public Nullable<decimal> VAT { get; set; }
        public Nullable<decimal> Total { get; set; }
    
        public virtual Retailshop Retailshop { get; set; }
        public virtual Retailshop Retailshop1 { get; set; }
        public virtual Retailshop Retailshop2 { get; set; }
    }
}
